version: '3.6'
networks: 
    backend:

volumes:
  caminhoesdata:
    
services:
  sql:
      container_name: database
      build:
        context: .
        dockerfile: Dockerfile.Infra
      volumes:
        - caminhoesdata:/var/lib/sql
      networks: 
        - backend
      ports:
        - 1433:1433    
